### ISSUE TITLE
Is logo image in README indicative of "nominal" wheel profile?

### ISSUE THREAD

**Issue by nmz787** [criogenox/A_Wheel-Rail-Contact-Characterization_WRCC#13]
I am interested to build a railcart (small powered vehicle for riding abandoned tracks), and I am looking for "ideal" design to implement. Given this will be for recreation, it need not be the most performant or resistant to wear and tear. Since your "importance" section clarifies that the "right" conicity will tradeoff turning well (not hitting inner flange) with straight-track comfort... which from [this youtube demo](https://youtu.be/HeDuGWNTDPY) I understand that comfort must mean less wobbling... I would like to know if the [blue wheel 2D profile ](https://user-images.githubusercontent.com/53323058/231350597-ae3f1833-2819-48bc-a582-9ab1341b847b.png)is the "ideal", even if just for your [country/region's] tracks in your [country/region's] gauge, etc... or is it, on the other hand, and extreme profile meant to showcase the conditions where performance is out-of-spec?

**Comment by criogenox** [comment]
Hi, my friend. You have 3 options: pure conical profile (which it's only a theoretical case), and a conformal wheel (variable conicity angle) with or without flange area. The picture you pointed out is clearly the case which lacks of flange zone (that technically speaking; it can be considered a very smoothed area in there, anyway). 

That said, the right wheel profile depends on the rail profile, and the need of flange is related to curving and speed specifications. 

But to keep it simple, assuming you won't build an TGV, I would use a conformal profile like the picture shows, according to your country's track dimensions.

Have a nice build journey.
Vincent.
